---

# Main tasks file for transparent-huge-pages role

- name: 'INIT | Manage variables to use for our target'
  import_tasks: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::transparent-huge-pages'
    - 'role::transparent-huge-pages::init'


- name: 'INSTALL | Manage services'
  include_tasks: "{{ role_path }}/tasks/manage_services.yml"
  tags:
    - 'role::transparent-huge-pages'
    - 'role::transparent-huge-pages::install'
